// AUTO-GENERATED by scripts/generate-project-screenshots.mjs — do not edit by hand.
// Run `npm run screenshots` to regenerate.
export const projectScreenshots: Record<string, string> = {
  'emergence-in-a-cup': '/images/projects/emergence-in-a-cup.png',
  'gle-asl': '/images/projects/gle-asl.png',
  'gle-coin-counter': '/images/projects/gle-coin-counter.png',
  'gle-components': '/images/projects/gle-components.png',
  'gle-gaussian-splat-3d': '/images/projects/gle-gaussian-splat-3d.png',
  'gle-pascal-voc': '/images/projects/gle-pascal-voc.png',
  'gle-potree': '/images/projects/gle-potree.png',
  'gle-r3f-components': '/images/projects/gle-r3f-components.png',
  'gle-roboflow-components': '/images/projects/gle-roboflow-components.png',
  'gle-roboflow-reinforcer': '/images/projects/gle-roboflow-reinforcer.png',
  'gle-roboflow-rest-client': '/images/projects/gle-roboflow-rest-client.png',
  'gle-scene-components': '/images/projects/gle-scene-components.png',
  'gle-threedtiles': '/images/projects/gle-threedtiles.png',
  'gle-vision-chat': '/images/projects/gle-vision-chat.png',
  gowiki: '/images/projects/gowiki.png',
  'guyettinger.github.io': '/images/projects/guyettinger.github.io.png',
  'pour-my-friends': '/images/projects/pour-my-friends.png',
};
